os: osx
osx_image: xcode12u
language: c
addons:
  homebrew:
    packages:
      autoconf
      automake
      libtool
before_script: autoreconf --install
script: ./configure && make && ./sshpass -h 2>/dev/null | grep -q used
